### PR TITLE
Added the events from Keen.io in a more angular way 

### PR DESCRIPTION
**Pull request by prbaron**
Use of promises instead of callbacks.

### CODE REVIEW

**Comment by theborakompanioni** [comment]
@prbaron Thank you! I am generally in favor of doing things more "angulary". Maybe I am missing something but instead of returning the Keen instance you return an object with just `addEvent` and `addEvents` methods -> the library itself uses additional methods e.g. `draw`.

So I am not completely sure if that is the right approach, what do you say?

**Comment by prbaron** [comment]
I am currently adding them. The idea is to get the same API, that means we will have this for adding an event : 
```
.controller('MyController', [
'$scope', 'tbkKeenClient', function($scope, Keen) {
  Keen.addEvent('collectionName', {
    here:  'are',
    your: 'properties'
  })
  .then(function(res) {
    console.log(res);
  })
  .catch(function (err) {
    console.error(err);
  });
}]);
```

and this to draw an event : 
```
```
.controller('MyController', [
'$scope', 'tbkKeenClient', function($scope, Keen) {
 var query = Keen.Query(...);
  Keen.run(query)
  .then(function(res) {
    console.log(res);
  })
  .catch(function (err) {
    console.error(err);
  });
}]);
```

**Comment by theborakompanioni** [comment]
I think it'd be better to not alter Keen's api, but rather provide additional methods perhaps prefixed with a distinct keyword (otherwise the api of keen must always be watched for changes. I don't think that is applicable).. then we can export `tbkKeenClient` like this:
```
return angular.extend(new Keen(KeenConfig), {
  prefixedAddEvents: addEvents,
  prefixedAddEvent: addEvent
});
```

**Comment by prbaron** [comment]
ok, I'll update the code so.

**Comment by theborakompanioni** [comment]
@prbaron Thank you so much for your effort! Two things I'd like to mention:
- "backwards"-compatibility for `tbkKeenMetric` is broken. I use it in a bunch of projects and rather keep it the way it is (e.g. prefix/postfix/scale params).
- Instead of changing the `tbkKeenClient` implementation, what do you think about a new service named `angularKeenClient` (or whatever) following this approach? There'd be no need for `getInstance` like methods and current users of the library would not have to adapt their code.

Looking forward to hearing your views.

**Comment by prbaron** [comment]
Hi,

Thank you for your interest ! 

  - Ok I will fix this, however, I tend to think that your previous tbkKeenMetric would be more a raw metric than the real Keenio metric to me.
  - I agree for this point and will reflect it in the code.

**Comment by prbaron** [comment]
I reintegrated the old services and added `angularKeenClient` so that the backward compatibility is fixed.

For the metric chart, I added your old metric chart in a directive called `tbkKeenRawMetric` as it does not use the Keen.io metric API and does not result in the official Keen.io chart. We then have the `tbkKeenRawMetric` and `tbkKeenMetric`.

**Comment by alebruck** [comment]
Heys guys, is this going to be merged? I was starting to write something like this and found your project. I would be happy to contribute here(especially because I'm planning to make production use of this code) but this PR has some good changes.

Thanks!

**Comment by theborakompanioni** [comment]
@alebruck I still have not had the time to review and try it. I'll assign a higher priority on this one :-)
In the meantime, have you had a chance to play with it?

**Comment by alebruck** [comment]
@theborakompanioni Thank you! 

I'll be testing it today and reporting any feedback during the weekend.

**Comment by theborakompanioni** [comment]
@prbaron Merged! Thanks for your contribution!
@alebruck Have you had success integrating it in your project?

**Comment by alebruck** [comment]
I actually failed on my first try. I'll do a second try today using the new v0.2

**Comment by theborakompanioni** [comment]
@alebruck k! You can always reach out to me if you're stuck / need some help.

**Pull request merged**
